debug: false

# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  devtools:
    restart:
      enabled: false

# ----------------------------------------------------------------------------------------------------------------------
# 日志配置
# ----------------------------------------------------------------------------------------------------------------------
logback:
  log-home: "/tmp"
  log-name: "skeleton"
