plugins {
    id 'base'
}

ext {
    // SpringBoot BOM 版本微调
    // https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html
    // https://docs.spring.io/spring-boot/appendix/dependency-versions/properties.html
}

allprojects {
    group = 'io.github.yingzhuo'
    version = '0.1.1'

    configurations.configureEach {
        resolutionStrategy {
            cacheChangingModulesFor 24, 'hours'
            cacheDynamicVersionsFor 24, 'hours'
        }
    }
}

tasks.named('wrapper') {
    distributionUrl = 'https://mirrors.cloud.tencent.com/gradle/gradle-9.6.1-bin.zip'
    validateDistributionUrl = false
}
