services:

  app:
    image: "io.github.yingzhuo/claude-playground/core:latest"
    container_name: "claude-playground-core"
    environment: { }
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    command:
      - "--spring.profiles.active=docker"
    depends_on: [ ]
