pluginManagement {
    repositories {
        mavenLocal()
        maven { url = 'https://maven.aliyun.com/repository/public/' }
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        maven { url = 'https://maven.aliyun.com/repository/public/' }
        mavenCentral()
    }

    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
}

rootProject.name = 'claude-playground'

include ':project-bom'

['projects-app', 'projects-lib'].each {
    file(it).eachDir { projectDir ->
        if (projectDir.directory && new File(projectDir, 'build.gradle').exists()) {
            include ":$it:${projectDir.name}"
        }
    }
}
