pluginManagement {
	repositories {
		mavenLocal()
		maven { url = 'https://maven.aliyun.com/repository/public/' }
		gradlePluginPortal()
		mavenCentral()
		maven { url = 'https://repo.spring.io/release' }
		maven { url = 'https://repo.spring.io/milestone' }
		maven { url = 'https://repo.spring.io/snapshot' }
	}
}

plugins {
	id 'io.spring.dependency-management' version "$dependencyManagementPluginVersion" apply false
	id 'org.springframework.boot' version "$springBootVersion" apply false
	id 'com.gorylenko.gradle-git-properties' version "$gitPluginVersion" apply false
	id 'com.google.cloud.tools.jib' version "$jibPluginVersion" apply false
}

dependencyResolutionManagement {
	repositories {
		mavenLocal()
		maven { url = 'https://maven.aliyun.com/repository/public/' }
		mavenCentral()
		gradlePluginPortal()
		maven { url = 'https://repo.spring.io/release' }
		maven { url = 'https://repo.spring.io/milestone' }
		maven { url = 'https://repo.spring.io/snapshot' }
	}

	repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
}

rootProject.name = 'claude-playground'

include ':project-bom'
include ':projects-app:core'
include ':projects-lib:addon-common'
include ':projects-lib:addon-model'
include ':projects-lib:addon-security'

include 'projects-lib:addon-redis'