pluginManagement {
	repositories {
		mavenLocal()
		maven { url = 'https://maven.aliyun.com/repository/public/' }
		gradlePluginPortal()
		maven { url = 'https://repo.spring.io/release' }
		maven { url = 'https://repo.spring.io/milestone' }
		maven { url = 'https://repo.spring.io/snapshot' }
		mavenCentral()
	}
}

dependencyResolutionManagement {
	var versionsToml = file('../gradle/libs.versions.toml')
	if (versionsToml.exists()) {
		versionCatalogs {
			create('libs', { from(versionsToml) })
		}
	}

	repositories {
		mavenLocal()
		maven { url = 'https://maven.aliyun.com/repository/public/' }
		mavenCentral()
		gradlePluginPortal()
		maven { url = 'https://repo.spring.io/release' }
		maven { url = 'https://repo.spring.io/milestone' }
		maven { url = 'https://repo.spring.io/snapshot' }
	}

	repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
}
