plugins {
    id 'java-platform'
}

description = '物料清单'

javaPlatform {
    allowDependencies()
}

dependencies {

    // BOM(s)
    api platform(libs.spring.boot.bom)
    api platform(libs.spring.moduilth.bom)
    api platform(libs.mybatis.plus.bom)
    api platform(libs.bouncycastle.bom)
    api platform(libs.hutool.bom)

    constraints {
        // 通用工具
        api 'com.google.guava:guava:33.6.0-jre'

        // mapstruct
        api 'org.mapstruct:mapstruct:1.6.3'
        api 'org.mapstruct:mapstruct-processor:1.6.3'

        // swagger
        api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

        // p6spy (SQL展示调试)
        api 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:2.0.1'

        // jwt
        api 'com.auth0:java-jwt:4.6.0'

        // uuid
        api 'com.fasterxml.uuid:java-uuid-generator:5.2.0'
    }
}
